server:
  port: 9005
  servlet:
    context-path: /
    session:
      timeout: 10 #초단위로 세션을 설정
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      
spring:
  application:
    name : fifth
  datasource:
    #url: jdbc:mysql://ljy-db.c60dwjop3klp.ap-northeast-1.rds.amazonaws.com:3306/THIRD_DB
    #url: jdbc:mysql://127.0.0.1:3306/THIRD_DB
    #url: jdbc:mysql://host.docker.internal:3306/THIRD_DB
    url: jdbc:log4jdbc:mysql://host.docker.internal:3306/FIFTH_DB
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #username: LJY_Amazon
    username: root
    password: ${DBPASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
    
sample:
  value: dev_test
  
  
mybatis:
  type-aliases-package: com.fifth.cms.mapper
  config-location : classpath:mybatis/sqlmap-config.xml
  #mapper-locations : mybatis/map/*.xml 설정은 1차적인 설정이라서 xml 파일을 매핑하지 않는다
  #, 2차적으로 하위 폴더에 있는 xml 파일을 찾아서 로드하게 해야함
  mapper-locations : mybatis/map/*/*.xml
  
# ========== log4jdbc  ==========

# jdbc.sqlonly - SQL문을 보여줌
# jdbc.sqltiming - SQL문과 SQL문 수행하는 시간을 같이 보여줌
# jdbc.resultsettable - SQL 의 결과로 조회된 데이터를 table 형태로 로그를 보여줌
# jdbc.audit - ResultSet 을 제외한 모든 JDBC 호출 정보를 로그로 보여줌, 상당히 많은 양의 로그가 나오기 때문에 권장하지 않음.
# jdbc.resultset - ResultSet 을 포함한 모든 JDBC 호출 정보를 로그로 보여줌, audit 처럼 많은 로그가 나오기 때문에 권장하지 않음.
# jdbc.connection - DB 연결, 연결 해제와 관련된 로그를 보여줌

# off - 사용하지 않음
# info - 정보성 로그
# warn - 경고성 로그
# error - 에러 로그
# fatal - 심각한 문제 로그

logging:
  level:
    jdbc: 
      sqlonly : off
      sqltiming : info
      resultsettable : off
      audit : off
      resultset : off
      connection : off
      
# ================================
